pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - Conflict
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
  - name: "auto add label=README"
    conditions:
      - files~=README.md
    actions:
      label:
        add: ["README"]
  - name: "auto add label=People"
    conditions:
      - files~=^(docs/people)
    actions:
      label:
        add: ["People"]
  - name: "auto add label=Templates"
    conditions:
      - files~=^(templates)
    actions:
      label:
        add: ["Templates"]
  - name: "auto add label=CI"
    conditions:
      - files~=^(ci/|.github/)
    actions:
      label:
        add: ["CI"]
  - name: "auto add label=Rendering"
    conditions:
      - files~=^render.py
    actions:
      label:
        add: ["Rendering"]
  - name: "auto add label=mergify"
    conditions:
      - files~=^.mergify.yml
    actions:
      label:
        add: ["mergify"]
